### ISSUE TITLE
Query 11 should have the filter value divided by the scale factor

### ISSUE THREAD

**Issue by PaulGVernon** [djouallah/Testing_BI_Engine#1]
Hi.

Looking at the TPC-H spec, query 11 should change based on the scale factor you are running at. E.g. you might like to use something like this

    SUM(ps_supplycost * ps_availqty) * (0.0001 / $scale_factor)

and set the scale_factor variable to, e.g. 10.   Otherwise, you could use `0.00001` of course.

As the query currently stands, I get 0 rows returned against the Snowflake SF10 schema.

**Comment by djouallah** [comment]
Thanks a lot, I did change it.
